name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libgdx:
    name: Check LibGDX import
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x ./gdx/check_import.sh
          bash ./gdx/check_import.sh ./gdx/build.gradle.kts
        shell: bash

  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run ktlint
        uses: lucasnlm/ktlint-action@master

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: |
          ./gradlew testFossDebugUnitTest --stacktrace


  fdroid:
    name: F-droid build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
     - name: Clone PR
       uses: actions/checkout@v2
       with:
         fetch-depth: 1
     - name: Setup JDK 17
       uses: actions/setup-java@v2
       with:
         distribution: 'zulu'
         java-version: '17'
     - name: Build for F-Droid
       run: |
         ./gradlew assembleFossDebug
