name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  libgdx:
    name: Check LibGDX import
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x ./gdx/check_import.sh
          bash ./gdx/check_import.sh ./gdx/build.gradle.kts
        shell: bash

ktlint:
    name: KtLint Auto-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "style: Auto-format by ktlint"
          git push

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: |
          ./gradlew testFossDebugUnitTest --stacktrace


  fdroid:
    name: F-droid build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
     - name: Clone PR
       uses: actions/checkout@v2
       with:
         fetch-depth: 1
     - name: Setup JDK 17
       uses: actions/setup-java@v2
       with:
         distribution: 'zulu'
         java-version: '17'
     - name: Build for F-Droid
       run: |
         ./gradlew assembleFossDebug
